# Default values for go-web-app-chart
# YAML-formatted file to declare variables passed into templates

replicaCount: 1

image:
  repository: smritisah/go-web-apps  # Your Docker Hub image
  pullPolicy: IfNotPresent
  tag: "v1"                          # Match the image tag you pushed

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific